import type { Diagram } from "../model/types";
import { defaultGrid } from "../model/defaults";

export const seedDiagram: Diagram = {
  id: "moschovakis-demo",
  title: "Moschovakis-style construction",
  grid: defaultGrid,
  stylePreset: "mosch",
  objects: [
    {
      id: "shade-tau",
      type: "shade-region",
      x: 1,
      y: 0,
      width: 12,
      height: 2.2,
      fill: "gray!18",
      roundedCorners: "6pt",
      layer: "background",
    },
    {
      id: "shade-sigma",
      type: "shade-region",
      x: 1,
      y: 3.15,
      width: 12,
      height: 2.55,
      fill: "gray!14",
      roundedCorners: "6pt",
      layer: "background",
    },
    {
      id: "box-tau",
      type: "box-label",
      tex: "\\tau",
      x: 0,
      y: 1,
      width: 0.8,
      height: 0.65,
      rounded: true,
    },
    {
      id: "box-sigma",
      type: "box-label",
      tex: "\\sigma",
      x: 0,
      y: 4.5,
      width: 0.8,
      height: 0.65,
      rounded: true,
    },
    { id: "row-i", type: "math-label", tex: "I", x: 1.45, y: 0.55, fontSize: "normal" },
    { id: "row-ii", type: "math-label", tex: "II", x: 1.42, y: 1.55, fontSize: "normal" },
    { id: "line-top-row", type: "grid-line", orientation: "horizontal", position: 1.08, start: 1.1, end: 12.5, style: "solid", arrowhead: "none" },
    { id: "line-middle", type: "grid-line", orientation: "horizontal", position: 2.72, start: 0.6, end: 13.2, style: "guide", arrowhead: "none" },
    { id: "line-bottom-row", type: "grid-line", orientation: "horizontal", position: 4.45, start: 1.1, end: 12.5, style: "solid", arrowhead: "none" },
    { id: "guide-left", type: "grid-line", orientation: "vertical", position: 2.2, start: 0.2, end: 5.5, style: "guide", arrowhead: "none" },
    { id: "t0", type: "math-label", tex: "t_0", x: 2.6, y: 0.55, fontSize: "normal" },
    { id: "t2", type: "math-label", tex: "t_2", x: 4.7, y: 0.55, fontSize: "normal" },
    { id: "t-top-dots", type: "ellipsis", x: 6.2, y: 0.55, orientation: "horizontal" },
    { id: "t1", type: "math-label", tex: "t_1=s_2\\setminus s_0", x: 3.45, y: 1.55, fontSize: "small" },
    { id: "t3", type: "math-label", tex: "t_3=s_4\\setminus s_0", x: 5.8, y: 1.55, fontSize: "small" },
    { id: "sigma-empty", type: "math-label", tex: "\\sigma(\\emptyset)=s_0", x: 2.95, y: 3.75, fontSize: "small" },
    { id: "s2", type: "math-label", tex: "s_2", x: 4.55, y: 3.75, fontSize: "normal" },
    { id: "s4", type: "math-label", tex: "s_4", x: 6.45, y: 3.75, fontSize: "normal" },
    { id: "diff0", type: "math-label", tex: "t_0\\setminus\\sigma(\\emptyset)", x: 3.2, y: 4.95, fontSize: "small" },
    { id: "diff2", type: "math-label", tex: "t_2\\setminus\\sigma(\\emptyset)", x: 5.35, y: 4.95, fontSize: "small" },
    { id: "lower-dots", type: "ellipsis", x: 7.8, y: 4.95, orientation: "horizontal" },
    { id: "right-vdots", type: "ellipsis", x: 12.15, y: 2.65, orientation: "vertical" },
    { id: "dot-a", type: "math-label", tex: "\\bullet", x: 8.9, y: 0.55, fontSize: "normal" },
    { id: "dot-b", type: "math-label", tex: "\\bullet", x: 10.0, y: 1.55, fontSize: "normal" },
    { id: "dot-c", type: "math-label", tex: "\\bullet", x: 8.9, y: 3.75, fontSize: "normal" },
    { id: "dot-d", type: "math-label", tex: "\\bullet", x: 10.0, y: 4.95, fontSize: "normal" }
  ],
  edges: [
    { id: "e-top-0", from: "t0", to: "t1", style: "solid", arrowhead: true },
    { id: "e-top-1", from: "t2", to: "t3", style: "solid", arrowhead: true },
    { id: "e-top-2", from: "dot-a", to: "dot-b", style: "solid", arrowhead: true },
    { id: "e-low-0", from: "sigma-empty", to: "diff0", style: "solid", arrowhead: true },
    { id: "e-low-1", from: "s2", to: "diff2", style: "solid", arrowhead: true },
    { id: "e-low-2", from: "dot-c", to: "dot-d", style: "solid", arrowhead: true },
    { id: "e-s2-t1", from: "s2", to: "t1", style: "solid", arrowhead: true },
    { id: "e-s4-t3", from: "s4", to: "t3", style: "solid", arrowhead: true },
    { id: "e-wave-t0", from: "t0", to: "diff0", style: "wavy", arrowhead: true },
    { id: "e-wave-t2", from: "t2", to: "diff2", style: "wavy", arrowhead: true }
  ],
};
